GuessingGame.Website/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GuessingGame.Website.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GuessingGame.Website/Pages/Index.cshtml.cs
using GuessingGame.Application;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

namespace GuessingGame.Website.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IGameRepository _gameRepository;
        private readonly string _gameIdSessionKey = "gameId";

        public string InputBoxMessage { get; private set; }
 
        public string InputBoxTitle { get; private set; }
        
        public int GuessLeft { get; private set; }
        public int Hintleft { get; private set; }

        public IndexModel(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }
        
        public void SetView(IGame game) 
        {
            GuessLeft = game.RemainingGuessAttempts;
            Hintleft = game.RemainingHintAttempts;
        }

        public void OnGet()
        {
            if (HttpContext.Session.IsAvailable)
            {
                InputBoxTitle = "Play Game";
                InputBoxMessage = "Number has been generated. Try Guessing it!";
            }

            var game = GetGameState();
            SetView(game);
        }

        public void OnPostHints()
        {
            InputBoxTitle = "HINT";
            var game = GetGameState();

            if (game.HasHints())
            {
                InputBoxMessage = game.GetHint();
            }
            else
            {
                InputBoxMessage = UserFeedback.NoHintsLeft();
            }
            SetView(game);
            _gameRepository.SaveGame(Guid.Parse(HttpContext.Session.GetString(_gameIdSessionKey)), game);
        }

        public void OnPostGuess()
        {
            InputBoxTitle = "ANSWER";

            var game = GetGameState();

            if (game.HasGuesses())
            {
                
                string playerGuess = Request.Form["getInput"];
                InputBoxMessage = FormInputHandler.CheckUserInput(ValidateUserInput.IsAnswerValid(playerGuess), game);
            }
            else
            {
                InputBoxMessage = UserFeedback.OffMessege();
                game.ResetGame();
            }

            SetView(game);
            _gameRepository.SaveGame(Guid.Parse(HttpContext.Session.GetString(_gameIdSessionKey)), game);
        }

        private IGame GetGameState()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(_gameIdSessionKey)))
            {
                var gameData = _gameRepository.CreateGame();
                HttpContext.Session.SetString(_gameIdSessionKey, gameData.Item1.ToString());
                return gameData.Item2;
            }
            else
            {
                var gameId = _gameRepository.GetGame(Guid.Parse(HttpContext.Session.GetString(_gameIdSessionKey)));
                return gameId;
            }
        }
    }
}

GuessingGame.Website/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuessingGame.Website.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GuessingGame.Website/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Guessing Game";
}

<div class="jumbotron text-center">
    <h1>Guessing Game</h1>
    <p>Let the games begin!</p>
</div>

<form method="post">
    
    <div class="container">
        
        <div class="text-center">
            
            <h3>HINTS:@Model.Hintleft</h3> 
            <h3>GUESSES LEFT:@Model.GuessLeft</h3>
            
            <div class="row ">
                <div class="Panel w-100 p-2" style="border:groove;border-color:black">
                    <nav class="navbar navbar-expand-sm bg-dark navbar-dark ">
                        <ul class="navbar-nav">
                            <li class="nav-itemEU">
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#HelpModal">
                                    Help
                                </button>
                            </li>

                        </ul>
                    </nav>

                    <h3> Guess the number</h3>
                    <input type="text" name="getInput" class="display-10 getInput" >

                    <div class="container">
                        <div class="alert alert-success alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>@Model.InputBoxTitle:</strong> @Model.InputBoxMessage
                        </div>
                    </div>

                    <hr style="background-color:darkgray" />
                    
                    <div class="container">
                        <input class="btn-dark" type="submit" asp-page-handler="Hints"
                               style="text-align:center" value=" Hint "  />
                        <input class="btn-dark" type="submit" asp-page-handler="Guess"
                               style="text-align:center" value=" Guess " />
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>


<div class="modal" id="HelpModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Game Instructions</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <dl>
                    <dt>Hint</dt>
                    <dd>- This buttom will give you information about the answer</dd>
                    <dt>Guess</dt>
                    <dd>- This will tell if you answer is correct or not</dd>
                </dl>
            </div>
            <!-- Modal footer -->
            
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

GuessingGame.Website/Pages/Shared/_Layout.cshtml
+<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuessingGame.Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">GuessingGame Website</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>